- name: test playboook
  become: true
  hosts: server
  vars_files:
    - secret.yml
  tasks:
    - name: ping
      ansible.builtin.ping:
    - name: command
      ansible.builtin.command: echo "{{ DB_PASSWORD }}" > /var/lib/jenkins/esra.txt